baseURL = "https://evilroot.eu.org/"
languageCode = "en-gb"
title = "evilroot's blog"
theme = "ghostwriter"
pygmentsCodefences = true
pygmentsUseClasses = true
disqusShortname = "evilroots-blog"
paginate = 5000 #frontpage pagination

[markup]
    [highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 2

[Author]
    name = "evilroot"
    profile = "https://twitter.com/evilr00t"

[Taxonomies]
    tag = "tags"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[menu]
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2
[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[params]
    intro = true
    title = "Software Engineering"
    slogan = "$ grep -rni \"The how's and why's\" ."
    headline = "Welcome to evilroot's blog"
    description = "rants, ideas, comments..."
    opengraph = true
    shareTwitter = true
    readingTime = true
    readingTimeText = "Estimated reading time:"
    dateFormat = "Mon, Jan 2, 2006"
    github = "https://github.com/evilr00t"
    linkedin = "https://linkedin.com/in/evilr00t/"
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true