baseURL = "https://evilroot.eu.org/"
languageCode = "en-gb"
title = "evilroot's blog"
theme = "ghostwriter"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsStyle = "colorful"
disqusShortname = "evilroots-blog"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
    name = "evilroot"
    profile = "https://twitter.com/evilr00t"

[Taxonomies]
    tag = "tags"

[Permalinks]
    post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[params]
    intro = true
    title = "Software Engineering"
    slogan = "$ grep -rni \"The how's and why's\" ."
    SEOTitle = "Rich Youngkin Blog"
    keyword = "Rich, Youngkin, Raspberry, Pi, Docker, Kubernetes, Go, Golang, Microservice"
    headline = "Welcome to evilroot's blog"
    description = "rants, ideas, comments..."
    opengraph = true
    shareTwitter = true
    readingTime = true
    readingTimeText = "Estimated reading time:"
    dateFormat = "Mon, Jan 2, 2006"
    github = "https://github.com/evilr00t"
    linkedin = "https://linkedin.com/in/evilr00t/"
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true